### ISSUE TITLE
RS256 key incorrect size issue?

### ISSUE THREAD

**Issue by lolgear** [jsonwebtoken/jsonwebtoken.github.io#276] opened 2017-11-27 16:42 UTC
In Objective-C implementation

https://github.com/yourkarma/JWT/tree/master/Example/JWTDesktop

the example RS256 public key from jwt.io causes error:

```
error: Error Domain=com.apple.security.transforms.error Code=6 "Invalid digest algorithm for RSA signature, choose one of: SHA1, SHA2 (512bits, 348bits, 256bits, or 224 bits), MD2, or MD5" UserInfo={NSDescription=Invalid digest algorithm for RSA signature, choose one of: SHA1, SHA2 (512bits, 348bits, 256bits, or 224 bits), MD2, or MD5}
```

When I check public key by SecKeyBlockSize, it shows 128 instead of expected 256.

Is it correct?
I suppose that hash size ( RS256 - 256 bit hash ) should match key length ( 256 ).

Is the example public key too short?

**Comment by Spomky** [comment] 2017-11-27 20:35
For the RSxxx algorithm, `xxx` refers to the hash algorithm, not the key size
You can sign a token with any size of key. Even a 16 bits key size is fine (but not secure at all!).

It looks like the bug comes from the implementation you mentions.

**Comment by sebadoom** [comment] 2017-12-01 15:38
Indeed, RS256 can be used with any valid RSA key of size 2048 bits or higher. This does not change the length of the resulting signature, which is determined by the hash algorithm. In the case of RS256 it must be SHA-256.

It would appear this is a bug in the Objective-C implementation. Do you have more information about this? Have you reported it to the maintainer of that implementation?

**Comment by lolgear** [comment] 2017-12-05 12:41
@Spomky @sebadoom yes, I asked Apple about implementation.

**Comment by sebadoom** [comment] 2017-12-05 22:23
@lolgear I think the problem is somewhere in this project, not in Apple's code: https://github.com/yourkarma/JWT

**Comment by lolgear** [comment] 2017-12-05 22:26
@sebadoom it would be nice to find it in project, but after error I've got a memory trap exception, which is not an expected behavior for Apple Security.framework.

**Comment by sebadoom** [comment] 2017-12-05 22:28
Obj-C, much like C, is tricky in the sense that memory corruption can cause seemingly unrelated problems later on. I hope you find the culprit. For the moment I'll close this issue. If you find that there is a problem with the key, please open a new issue. Thanks.

**Closed by sebadoom** 2017-12-05 22:28 UTC
Labels: blocked-awaiting-input, invalid
