### ISSUE TITLE
Text input does not work on iOS/Android

### ISSUE THREAD

**Issue by ntotten** [jsonwebtoken/jsonwebtoken.github.io#44] opened 2015-03-06 16:58 UTC
There are a few issues I found:

When clicking on the textbox and holding the delete key only one character is deleted and the delete key is released. The expected iOS behavior is that you can click and hold to continually delete.
You cannot click and hold to select the text thus making it difficult to clear the textbook.
You cannot click and hold to copy or paste. Paste is most problematic because it makes the site impossible to use on iOS unless you memorize and type the key manually.
Here is a video of the interactions. At then end you will see me trying to click, click and hold, etc.

https://www.dropbox.com/s/26bw8lkp380k8lv/2015-02-06_12-24-24.mp4?dl=0

My guess is we are just intercepting too many events incorrectly. One nice thing would be on mobile browsers that once you click on the text box it automatically clears then the user can easily paste in the box.

**Comment by pose** [comment] 2015-08-04 19:59
@ntotten can you check if with the new UI it can still be reproduced? Thanks!

**Comment by ntotten** [comment] 2015-08-12 05:04
Yeah, it still happens.

**Comment by sebadoom** [comment] 2017-11-17 19:29
This is probably caused by the library we use to render and colorize the input boxes. We need to check if there are updates that fix these issues. I can confirm they still happen on iOS 11.

**Comment by sebadoom** [comment] 2017-12-11 14:49
We will review this again after the library updates planned for stage 3.

**Comment by sebadoom** [comment] 2018-03-24 01:02
This appears to be fixed in HEAD (and live at https://jwt.io). Please reopen if not. Thanks.

**Closed by sebadoom** 2018-03-24 01:02 UTC
Labels: bug, high-priority, stage-3
